### PR TITLE
💬 Let's use GitHub Discussions

### PR DESCRIPTION
**Pull request by tkoyama010**
See https://github.com/pyvista/pyvista/pull/1395

### CODE REVIEW

**Comment by tkoyama010** [comment]
This is a redirection of `pyvista-support` to `pyvista` GitHub Discussion. Pinning @pyvista/developers .

**Comment by adeak** [comment]
I'm not sure this is according to plan. In https://github.com/pyvista/pyvista/pull/1395#issuecomment-864576364 @akaszynski said

> My vote is to keep support going and then evaluate in a few months if people have figured out discussions, etc

and in https://github.com/pyvista/pyvista/pull/1395#issuecomment-864603439

> `pyvista-support` can be undocumented. We'll still let people use it, and we need to preserve its history. We may return should this discussions thing not work out.

I understood this as a plan to leave `pyvista-support` alone for now, allowing people to post there. We'd just remove signposts pointing people to the support repo (which we have).

**Comment by tkoyama010** [comment]
@adeak Thank you for comment. This PR should keep it as a draft until judging that we can use GitHub Discussion.

**Comment by akaszynski** [comment]
> I understood this as a plan to leave pyvista-support alone for now, allowing people to post there. We'd just remove signposts pointing people to the support repo (which we have).

Agreed.  Lets transition this slowly and see who uses what as soon as our docs reflect the usage of discussions.  It's possible that discussions doesn't scale.

**Pull request merged**
